all:
	+$(MAKE) -C heightmap
	+$(MAKE) -C obj_loading
	+$(MAKE) -C skybox
	+$(MAKE) -C yaw_pitch_roll
clean:
	+$(MAKE) clean -C heightmap
	+$(MAKE) clean -C obj_loading
	+$(MAKE) clean -C skybox
	+$(MAKE) clean -C yaw_pitch_roll
