all:
	+$(MAKE) -C audio
	+$(MAKE) -C core
	+$(MAKE) -C models
	+$(MAKE) -C shaders
	+$(MAKE) -C textures
clean:
	+$(MAKE) clean -C audio
	+$(MAKE) clean -C core
	+$(MAKE) clean -C models
	+$(MAKE) clean -C shaders
	+$(MAKE) clean -C textures
