all:
	+$(MAKE) -C 3d_camera_first_person
	+$(MAKE) -C 3d_camera_free
	+$(MAKE) -C 3d_mode
	+$(MAKE) -C 3d_picking
	+$(MAKE) -C basic_window
	+$(MAKE) -C color_select
	+$(MAKE) -C drop_files
	+$(MAKE) -C input_keys
	+$(MAKE) -C input_mouse
	+$(MAKE) -C mouse_wheel
	+$(MAKE) -C random_values
clean:
	+$(MAKE) clean -C 3d_camera_first_person
	+$(MAKE) clean -C 3d_camera_free
	+$(MAKE) clean -C 3d_mode
	+$(MAKE) clean -C 3d_picking
	+$(MAKE) clean -C basic_window
	+$(MAKE) clean -C color_select
	+$(MAKE) clean -C drop_files
	+$(MAKE) clean -C input_keys
	+$(MAKE) clean -C input_mouse
	+$(MAKE) clean -C mouse_wheel
	+$(MAKE) clean -C random_values
